export const naivebayesnetworks = {
  bayesiannet: {
    nodes: [
      {
        id: "Age",
        name: "Age",
        label: "Age",
        parents: [],
        x: 400,
        y: 50,
        fixed: true,
      },
      {
        id: "Income",
        name: "Income",
        label: "Income",
        parents: ["Age"],
        x: 550,
        y: 150,
        fixed: true,
      },
      {
        id: "Head of Household",
        name: "Head of Household",
        label: "Head of Household",
        parents: ["Age"],
        x: 250,
        y: 350,
        fixed: true,
      },
      {
        id: "CC",
        name: "CC",
        label: "CC",
        parents: ["Age", "Head of Household"],
        x: 250,
        y: 150,
        fixed: true,
      },

      {
        id: "Invests in X",
        name: "Invests in X",
        label: "Invests in X",
        parents: ["CC", "Head of Household", "Income"],
        x: 600,
        y: 350,
        fixed: true,
      },
    ],
    probabilities: {
      Age: {
        "Age=Young": 0.3,
        "Age=Middle": 0.4,
        "Age=Old": 0.3,
      },
      Income: {
        "Income=Low": 0.4,
        "Income=Medium": 0.4,
        "Income=High": 0.2,
      },
      "Head of Household": {
        "Head of Household=Yes|Age=Young": 0.2,
        "Head of Household=No|Age=Young": 0.8,
        "Head of Household=Yes|Age=Middle": 0.5,
        "Head of Household=No|Age=Middle": 0.5,
        "Head of Household=Yes|Age=Old": 0.7,
        "Head of Household=No|Age=Old": 0.3,
      },
      CC: {
        "CC=Yes|Age=Young,Head of Household=Yes": 0.6,
        "CC=No|Age=Young,Head of Household=Yes": 0.4,
        "CC=Yes|Age=Young,Head of Household=No": 0.3,
        "CC=No|Age=Young,Head of Household=No": 0.7,
        "CC=Yes|Age=Middle,Head of Household=Yes": 0.7,
        "CC=No|Age=Middle,Head of Household=Yes": 0.3,
        "CC=Yes|Age=Middle,Head of Household=No": 0.4,
        "CC=No|Age=Middle,Head of Household=No": 0.6,
        "CC=Yes|Age=Old,Head of Household=Yes": 0.8,
        "CC=No|Age=Old,Head of Household=Yes": 0.2,
        "CC=Yes|Age=Old,Head of Household=No": 0.5,
        "CC=No|Age=Old,Head of Household=No": 0.5,
      },
      "Invests in X": {
        "Invests in X=Yes|CC=Yes,Head of Household=Yes,Income=Low": 0.7,
        "Invests in X=No|CC=Yes,Head of Household=Yes,Income=Low": 0.3,
      },
      evidence: {},
    },
  },
  naivebayesnets: {
    nodes: [
      {
        id: "Invests in X",
        name: "Invests in X",
        label: "Invests in X",
        parents: [],
        x: 450,
        y: 50,
        fixed: true,
      },
      {
        id: "Age",
        name: "Age",
        label: "Age",
        parents: ["Invests in X"],
        x: 300,
        y: 250,
        fixed: true,
      },
      {
        id: "Income",
        name: "Income",
        label: "Income",
        parents: ["Invests in X"],
        x: 375,
        y: 250,
        fixed: true,
      },
      {
        id: "Head of Household",
        name: "Head of Household",
        label: "Head of Household",
        parents: ["Invests in X"],
        x: 600,
        y: 250,
        fixed: true,
      },
      {
        id: "CC",
        name: "CC",
        label: "CC",
        parents: ["Invests in X"],
        x: 525,
        y: 250,
        fixed: true,
      },
    ],
  },
};
